name: Build zip package on version tag and upload to release

on:
  push:
    tags:
      - '*'

jobs:
  build:
    name: Build
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - name: Install Composer dependencies
        run: composer install --no-dev --no-progress --no-suggest
      - name: Build zip package
        run: zip -r upvoty-wp-integration.zip upvoty-wp-integration -x "**/*.git*" "**/_*" "*pipelines.yml" "**/.gitignore" "**/composer.json" "**/composer.lock" "**/*.sass-cache*" "**/.babelrc" "**/.editorconfig" "**/package-lock.json" "**/test/**" "**/README.md" "**/readme.md" "**/vendor/tangible/builder*"
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
      # @see https://github.com/actions/upload-release-asset
      - name: Upload Release Asset
        id: upload_release_asset
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps
          asset_path: ./upvoty-wp-integration.zip
          asset_name: upvoty-wp-integration.zip
          asset_content_type: application/zip
